### PR TITLE
ADD mapping from id to dsp in game id

### PR DESCRIPTION
**Pull request by GripenANM**
Used data parser from nexil to get in game data and map the factorial lab id to in game id.

### CODE REVIEW

**Comment by GripenANM** [comment]
Updated the map.json thanks to the help from Raptor for cross-checking and verifying it

**Comment by dcbroad3** [comment]
Can we do this as an object where the key is the DSP id and the value is the FactorioLab id? (Or the reverse) I would assume that will be a lot easier to use, object lookups are much better than searching an array.

**Comment by GripenANM** [comment]
oh ya definitely

**Comment by GripenANM** [comment]
there

**Comment by dcbroad3** [comment]
I forgot you can't have real numeric keys in json, but yeah, this will do fine

**Pull request merged**
