### PR TITLE
Count and display modules tally, closes #824

### LINKED ISSUE #824: Add module counts to totals row

### PR DESCRIPTION
**Pull request by zohnannor**
This is how it looks:

image

Closes #824

### CODE REVIEW

**Comment by dcbroad3** [comment]
Very nice, looks pretty good! Let me know when you think it's ready, main issue I see is getting the tests passing.

**Comment by dcbroad3** [comment]
One suggestion: It might be nicer to show the module counts in a separate pseudo-column next to the factory totals, to make it clear it's a separate list. 
image

**Comment by zohnannor** [comment]
Yes, I thought of it as well! My HTML and Angular skills arent great by I'll try my best!

**Comment by zohnannor** [comment]
Hey! Would this suffice?

image

**Comment by dcbroad3** [comment]
> Hey! Would this suffice?

Looks perfect to me

**Comment by dcbroad3** [comment]
Thanks for the contribution! I might fiddle with updating tests and tweaking the css a little in a followup PR but no need for you to worry about that.

**Pull request merged**
