### PR TITLE
fix: Update the Chinese translations

### PR DESCRIPTION
**Pull request by CloudBillow**

### CODE REVIEW

**Comment by CloudBillow** [comment]
Hi~ Could you let me know how to translate the circled text in the image? Did you unpack it from the game yourself, or does it need a separate translation?

image

**Comment by dcbroad3** [comment]
Data for specific data sets is in a different location: The file you're looking for is `src/data/spa/i18n/zh.json`. It is missing keys for all of the new items from Space Age. 
Actually, it should be possible to update that file from game data directly. I'll open a ticket to look into it. The old mod I built to dump data was set up to build translation files if necessary, but I don't think I ever updated the new scripts to do it. 
You shouldn't have to add those translations manually, though.

I just updated the `main` branch so that the `tests` action should skip the steps it cannot run successfully when running on a PR from a fork. Could you try merging from main and see if the tests pass now? If not, I can bypass them again.

**Comment by dcbroad3** [comment]
https://github.com/factoriolab/factoriolab/issues/1613

**Comment by CloudBillow** [comment]
retry

**Pull request closed without merging**
